### ISSUE TITLE
Add boolean property to lock rotation

### ISSUE THREAD

**Issue by AdrianVovk** [WayfireWM/wayfire-plugins-extra#1]
It's very much of a hack to load/unload the autorotate plugin. It'd be nice if carbonSHELL can just change a boolean property in the config file to toggle the autorotate functionality

**Comment by AdrianVovk** [comment]
Could this, instead of messing with a config file, just listen to a gsetting? GNOME sets `org.gnome.settings-daemon.peripherals.touchscreen orientation-lock` to true to disable screen rotation. cSH does the same now.

**Comment by ammen99** [comment]
I will implement a config file option, and we can add a toggle lock binding. If you want to, you can clone the plugin and add support for the gnome thing that you said.

**Comment by AdrianVovk** [comment]
@ammen99 Alright. I'll be implementing a gsettings --> wf-config plugin anyway (I've forgotten about this), so that's fine

**Comment by ammen99** [comment]
I added an option in https://github.com/WayfireWM/wayfire-plugins-extra/commit/749f55a536103bdc9489256866b2829aecc23e93 , it is named `lock_rotation`.

Alternatively, the user can use a keyboard shortcut to set the rotation, which will automatically lock it. Pressing the same rotation twice will unlock it again (i.e you can rotate left, rotation gets locked to 90 degrees, then press the binding for rotate left again, rotation starts following sensor data)
