### ISSUE TITLE
Fails to build with 2021-11-14 snapshot

### ISSUE THREAD

**Issue by jbeich** [WayfireWM/wayfire-plugins-extra#104]
Regressed by [wlroots@76bab68](https://gitlab.freedesktop.org/wlroots/wlroots/-/commit/76bab68e701b). From [error log](https://github.com/WayfireWM/wayfire-plugins-extra/files/7541217/wayfire-plugins-extra-0.7.0.21.log):
```c++
src/mag.cpp:178:14: error: use of undeclared identifier 'wlr_output_export_dmabuf'; did you mean 'wlr_output_event_damage'?
        if (!wlr_output_export_dmabuf(output->handle, &dmabuf_attribs))
             ^
/usr/include/wlr/types/wlr_output.h:195:8: note: 'wlr_output_event_damage' declared here
struct wlr_output_event_damage {
       ^
```

**Comment by soreau** [comment]
Does #105 help?

**Comment by jbeich** [comment]
I confirm, [builds fine](https://github.com/WayfireWM/wayfire-plugins-extra/files/7541357/wayfire-plugins-extra-0.7.0.21.log) after applying #105 (d028dec4934c).

**Comment by soreau** [comment]
I will wait for wayfire #1342 and then merge #106 instead of #105. Thanks for reporting this.
