### ISSUE TITLE
V7 branch does not compile

### ISSUE THREAD

**Issue by UltraBlackLinux** [WayfireWM/wayfire-plugins-extra#122]
Hey there,
I am having trouble compiling the v7 branch, I always just get this error: 
```
FAILED: src/libmag.so.p/mag.cpp.o
../src/mag.cpp: In lambda function:
../src/mag.cpp:178:14: error: ‘wlr_output_export_dmabuf’ was not declared in this scope; did you mean ‘wlr_output_event_damage’?
  178 |         if (!wlr_output_export_dmabuf(output->handle, &dmabuf_attribs))
      |              ^~~~~~~~~~~~~~~~~~~~~~~~
      |              wlr_output_event_damage
[28/37] Compiling C++ object src/libworkspace-names.so.p/workspace-names.cpp.o
ninja: build stopped: subcommand failed.
```
I can't build master because I got some packages depending on wayfire, wayfire-git doesn't seem to be an option for those (I installed wayfire from the arch repos)
Are you able to fix this, or is that a problem on my side?
Thanks!

**Comment by UltraBlackLinux** [comment]
Huh, the build only seems to succeed while running the wayfire-git package

**Comment by HVisMyLife** [comment]
Same error here, and I can't install wayfire-git (compilation error: ERROR: Automatic wrap-based subproject downloading is disabled )...

**Comment by UltraBlackLinux** [comment]
@HVisMyLife No... Not "Same error here" - Your error is completely different??

**Comment by HVisMyLife** [comment]
> @HVisMyLife No... Not "Same error here" - Your error is completely different??

Sorry, I mean, that error is for wayfire-git... 
While compiling plugins it's the same

**Comment by ammen99** [comment]
> Same error here, and I can't install wayfire-git (compilation error: ERROR: Automatic wrap-based subproject downloading is disabled )...

There were some recent changes, I'd recommend submitting a bug report to the packages.
