### ISSUE TITLE
Background-view does nothing

### ISSUE THREAD

**Issue by UltraBlackLinux** [WayfireWM/wayfire-plugins-extra#124]
Hey there,
I just wanted to set up background view for use with linux-wallpaperengine, but it turns out, that it refuses to do anything when toggled, even with the default mpv settings and just a file selected. I remember that it was working at some point, but I accidently exited mpv with my quit keybind, followed by wayfire crashing.
I am running `wayfire-git r2199.94f15048-1` and `wayfire-plugins-extra-git r148.bcadd22-1` installed from the AUR.
Why is this happening? Is it a known issue which has an easy solution?
Thanks!

**Comment by soreau** [comment]
Have you checked the wayfire log to see if there was a problem loading it? It's possible w-p-e plugins need to be rebuilt.

**Comment by UltraBlackLinux** [comment]
> Have you checked the wayfire log to see if there was a problem loading it? It's possible w-p-e plugins need to be rebuilt.

Welp it seem like rebuilding might have actually fixed it, thank you! It's working as it should, I am very pleased

**Comment by UltraBlackLinux** [comment]
Oh it seems as if this is not entirely solved. When booting into wayfire I have to toggle the background view twice for it to apply, otherwise it will just show the default wallpaper. This can't be intentional.

**Comment by soreau** [comment]
> Oh it seems as if this is not entirely solved. When booting into wayfire I have to toggle the background view twice for it to apply, otherwise it will just show the default wallpaper. This can't be intentional.

If you only want linux-wallpaper, then maybe have autostart not start wf-background in the first place.

**Comment by UltraBlackLinux** [comment]
> > Oh it seems as if this is not entirely solved. When booting into wayfire I have to toggle the background view twice for it to apply, otherwise it will just show the default wallpaper. This can't be intentional.
> 
> If you only want linux-wallpaper, then maybe have autostart not start wf-background in the first place.

Oh yeah right, I forgot to remove that. Does it overlay over background view?

**Comment by soreau** [comment]
I think when multiple surfaces request to be background, the last one wins. Wayfire doesn't try to manage a particular stacking order in this case.

**Comment by UltraBlackLinux** [comment]
Welp, removing wf-background from autostart seems to have fixed this. Thanks again, I need to get used to such modularity xD
