### ISSUE TITLE
Background-view very unstable

### ISSUE THREAD

**Issue by UltraBlackLinux** [WayfireWM/wayfire-plugins-extra#128]
Hey there,
I've been using background-view for quite a while now, but it's a bit unstable, if you are using programs that need to be restarted to apply settings.
It mostly seems to come down to wayfire crashing, when starting/stopping the background-view plugin while the background process is dead.
Please fix this, I assume that the other toggling crashes will be fixed by something like this!
Thanks!

**Comment by soreau** [comment]
Hi, if you need to restart the app, a workaround could be to toggle the plugin disabled/enabled, while the app is still running. This should restart the app in question. This would only be a workaround, of course we don't want wayfire to ever crash. I will have to look into this further to see how we can fix it.

**Comment by UltraBlackLinux** [comment]
This is sadly not really a workaround, if the program crashed when it's started, so wayfire will crash trying to kill the process.

**Comment by soreau** [comment]
Can you post the backtrace from wayfire when it crashes? It should be the last thing in the log, which is the stdout of wayfire.

**Comment by soreau** [comment]
Can you see if #129 fixes the issue you are having?

**Comment by UltraBlackLinux** [comment]
> Can you see if #129 fixes the issue you are having?

This did fix the instability issues, but now the background-view windows are no longer in the background, but rather opened as a seperate window, and this on every desktop

**Comment by soreau** [comment]
Are you sure you have set the application identifier field correctly? It must match the app-id for the window or else it won't be placed on the background. If you don't know what it is, wayfire outputs this information in the log.

**Comment by UltraBlackLinux** [comment]
> Are you sure you have set the application identifier field correctly? It must match the app-id for the window or else it won't be placed on the background. If you don't know what it is, wayfire outputs this information in the log.

I am sure, yeah. It was working before, when it was very unstable

**Comment by soreau** [comment]
Yes but before, there were two mechanisms. One for app-id and another for pid match. Since pid matching is unreliable, I removed this, so the app-id must match or else it won't work. It is working here in my tests, so I think that you should double or triple check the app-id is correct including case.

**Comment by soreau** [comment]
another way to check the app-id is with wf-prop which is included with dbus plugin, which is built when passing `-Denable_dbus=true` to w-p-e meson. Run wf-prop in a terminal, click the window and see the app-id for it.

**Comment by UltraBlackLinux** [comment]
> Yes but before, there were two mechanisms. One for app-id and another for pid match. Since pid matching is unreliable, I removed this, so the app-id must match or else it won't work. It is working here in my tests, so I think that you should double or triple check the app-id is correct including case.

is the app-id now what you see as process name in os aux?

**Comment by soreau** [comment]
No, the app-id is something different. Applications set their [app id](https://wayland.app/protocols/xdg-shell#xdg_toplevel:request:set_app_id:arg:app_id) using the wayland xdg protocol. If you install and enable dbus plugin, wf-prop will be available and it's probably the best/easiest way to get the app-id for any surface, reliably.

**Comment by UltraBlackLinux** [comment]
> another way to check the app-id is with wf-prop which is included with dbus plugin, which is built when passing `-Denable_dbus=true` to w-p-e meson. Run wf-prop in a terminal, click the window and see the app-id for it.
> 
> EDIT: Don't forget to enable dbus plugin first.

Trying this failed annoyingly: 
```
../subprojects/dbus/dbus_interface.cpp:28:10: fatal error: wayfire/plugins/common/view-change-viewport-signal.hpp: No such file or directory
   28 | #include <wayfire/plugins/common/view-change-viewport-signal.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```
I figured this is supposed to be shipped with wayfire-git, but the file just doesn't exist there.

**Comment by soreau** [comment]
Aha, thanks for letting me know. Apparently I still have this file from old. You will have to install it separately from [here](https://github.com/soppelmann/wayfire-plugin_dbus_interface) or apply [this patch](https://github.com/soppelmann/wayfire-plugin_dbus_interface/commit/dbd06ec085851c4e08bc984bb7903b9b363b654b) to subprojects/dbus.

**Comment by UltraBlackLinux** [comment]
> Aha, thanks for letting me know. Apparently I still have this file from old. You will have to install it separately from [here](https://github.com/soppelmann/wayfire-plugin_dbus_interface) or apply [this patch](https://github.com/soppelmann/wayfire-plugin_dbus_interface/commit/dbd06ec085851c4e08bc984bb7903b9b363b654b) to subprojects/dbus.

```
FAILED: subprojects/dbus/wf-prop.p/wf-prop.cpp.o
ccache c++ -Isubprojects/dbus/wf-prop.p -Isubprojects/dbus -I../subprojects/dbus -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/sysprof-4 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/giomm-2.4 -I/usr/lib/giomm-2.4/include -I/usr/include/glibmm-2.4 -I/usr/lib/glibmm-2.4/include -I/usr/include/sigc++-2.0 -I/usr/lib/sigc++-2.0/include -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -std=c++17 -O3 -DWLR_USE_UNSTABLE -DWAYFIRE_PLUGIN -pthread -MD -MQ subprojects/dbus/wf-prop.p/wf-prop.cpp.o -MF subprojects/dbus/wf-prop.p/wf-prop.cpp.o.d -o subprojects/dbus/wf-prop.p/wf-prop.cpp.o -c ../subprojects/dbus/wf-prop.cpp
In file included from /usr/include/glib-2.0/glib/glib-typeof.h:39,
                 from /usr/include/glib-2.0/glib/gatomic.h:28,
                 from /usr/include/glib-2.0/glib/gthread.h:32,
                 from /usr/include/glib-2.0/glib/gasyncqueue.h:32,
                 from /usr/include/glib-2.0/glib.h:32,
                 from /usr/include/glib-2.0/gobject/gbinding.h:28,
                 from /usr/include/glib-2.0/glib-object.h:22,
                 from /usr/include/glib-2.0/gio/gioenums.h:28,
                 from /usr/include/glib-2.0/gio/giotypes.h:28,
                 from /usr/include/glib-2.0/gio/gio.h:26,
                 from ../subprojects/dbus/wf-prop.cpp:10:
/usr/include/c++/12.1.0/type_traits:44:3: error: template with C linkage (a lot of these now, somewhat the same)
```
What is this now - I just applied the patch

**Comment by soreau** [comment]
This should do the trick, if ran starting from the wayfire-plugins-extra directory:

```
cd subprojects/dbus
git reset --hard HEAD
git checkout c705bf1
git pull origin master
curl https://github.com/soppelmann/wayfire-plugin_dbus_interface/commit/dbd06ec085851c4e08bc984bb7903b9b363b654b.diff | git apply
cd ../..
```
then try the build again.

**Comment by UltraBlackLinux** [comment]
> This should do the trick, if ran starting from the wayfire-plugins-extra directory:
> 
> ```
> cd subprojects/dbus
> git reset --hard HEAD
> git checkout c705bf1
> git pull origin master
> curl https://github.com/soppelmann/wayfire-plugin_dbus_interface/commit/dbd06ec085851c4e08bc984bb7903b9b363b654b.diff | git apply
> cd ../..
> ```
> 
> then try the build again.

Oh yeah this worked, so I guess I applied the patch incorrectly? 

So how do I use wf-prop? there is no way to set a window for it to scan xD

**Comment by soreau** [comment]
Well first you have to restart wayfire since installing a new plugin so the metadata is read by wf-config. Then you need to enable dbus. Once you have dbus plugin enabled, you run wf-prop in a terminal and the cursor will turn into a crosshair. Then you click on any window and wf-prop will return information about the window in the terminal.

**Comment by UltraBlackLinux** [comment]
I did enable dbus and didn't have to restart wayfire, but just tried logging out and back in again, and yet wf-prop refuses to show the crosshair-cursor. The wayfire dbus interface doesn't exist either.

**Comment by soreau** [comment]
It sounds like dbus isn't enabled for your session. You can also find the app-id in the log, which is the stdout of wayfire. If you redirect the output of wayfire to file, then that is the log. You can find the app-id there, which appears as a message like this:
```
II 21-05-22 12:01:02.836 - [src/view/xdg-shell.cpp:201] new xdg_shell_stable surface: Wayfire Config Manager app-id: wcm
```
So when you enable background-view and it starts the app, there should be some messages like this in the log and you can match the app-id in the plugin.

**Comment by UltraBlackLinux** [comment]
> It sounds like dbus isn't enabled for your session. You can also find the app-id in the log, which is the stdout of wayfire. If you redirect the output of wayfire to file, then that is the log. You can find the app-id there, which appears as a message like this:
> 
> ```
> II 21-05-22 12:01:02.836 - [src/view/xdg-shell.cpp:201] new xdg_shell_stable surface: Wayfire Config Manager app-id: wcm
> ```
> 
> So when you enable background-view and it starts the app, there should be some messages like this in the log and you can match the app-id in the plugin.

Dbus is enabled, and I am actively using it for some compatibility stuff I read about in the wayfire wiki (dbus-update-activation-environment --systemd WAYLAND_DISPLAY DISPLAY XAUTHORITY XDG_CURRENT_DESKTOP)

Also how do I obtain those logs. They don't get sent to journalctl. I can open a mini-wayfire inside of wayfire, but I can't open programs there because all keybinds just open programs in my window

... Why is it so hard to just get the background-view to work

**Comment by soreau** [comment]
when you open wayfire nested inside of wayfire, you should see the output in the terminal. So `wayfire |& grep app-id` and then start the app, it should spit the id.

**Comment by UltraBlackLinux** [comment]
> when you open wayfire nested inside of wayfire, you should see the output in the terminal. So `wayfire |& grep app-id` and then start the app, it should spit the id.

... this is weird: `new xdg_shell_stable surface: WallpaperEngine app-id: (null)`

**Comment by soreau** [comment]
Ok, so just make the app-id blank?

**Comment by UltraBlackLinux** [comment]
> Ok, so just make the app-id blank?

isn't that kinda dangerous if other apps also get blank app-ids?

**Comment by soreau** [comment]
After doing some debugging, you should set it to "nil" and it should match. There shouldn't be any danger matching other apps because it only matches the first nil app-id after launching the app, and ignores others after that.

**Comment by UltraBlackLinux** [comment]
Yep, I can confirm, that nil works, though one question still persists: Why is dbus not working? I would love to use wf-msg, since I think swaymsg is a very useful program. Also wf-robs seems pretty useful, but I can't use that if the dbus thing does not appear when enabling the dbus plugin

**Comment by marcusbritanicus** [comment]
@UltraBlackLinux you'll have to debug it by starting a wayfire session in your currently running session. If there was some problem in loading the dbus plugin, that would be printed on the terminal output of your new wayfire session.

However, I wonder how it could be related to `glib-main-loop`: when you enable dbus, `glib-main-loop` is automatically loaded.

**Comment by soreau** [comment]
I built the same dbus code I had you build and it is indeed broken as you described. To get it working here I did this:
```
cd subprojects/dbus
git reset --hard c705bf1
curl http://ix.io/3YmU | git am
cd ../..
```
build dbus again.

**Comment by UltraBlackLinux** [comment]
> I built the same dbus code I had you build and it is indeed broken as you described. To get it working here I did this:
> 
> ```
> cd subprojects/dbus
> git reset --hard c705bf1
> curl http://ix.io/3YmU | git am
> cd ../..
> ```
> 
> build dbus again and restart wayfire.

Back to [this](https://github.com/WayfireWM/wayfire-plugins-extra/issues/128#issuecomment-1133756525) again. This is a very annoying procedure apparently.

**Comment by soreau** [comment]
Yes, I think you need [this](https://github.com/damianatorrpm/wayfire-plugin_dbus_interface/commit/c7cc8e11e7f8fa2b725eb8feab6d05a8242709e7) so I added it to the patch. Run the same set of commands again to apply the patch again.

**Comment by UltraBlackLinux** [comment]
Yep, that worked. Dbus is now visible in the list of dbus compositors and wf-prob works (only the crosshair doesn't, but that's a minor issue, that you can probably ignore)

Please push this, I don't want it gone, when I update WPE
