### ISSUE TITLE
XKill Alternative

### ISSUE THREAD

**Issue by UltraBlackLinux** [WayfireWM/wayfire-plugins-extra#130]
Hey there,
I really enjoyed using xKill, when I was on kde, but now on wayfire, this is no longer available. I would be really happy, if this could be ported to and integrated into wayfire!
Thanks!

**Comment by soreau** [comment]
You should be able to use [this](https://github.com/soreau/wf-kill).

**Comment by UltraBlackLinux** [comment]
> You should be able to use [this](https://github.com/soreau/wf-kill).

Awesome!
