### ISSUE TITLE
Subcommand failed on compilation

### ISSUE THREAD

**Issue by Tryware** [WayfireWM/wayfire-plugins-extra#135]
```
ninja -C build && sudo ninja -C build install
ninja: Entering directory `build'
[8/43] Compiling C++ object s...iew-shot.so.p/view-shot.cpp.o
FAILED: src/libview-shot.so.p/view-shot.cpp.o
ccache c++ -Isrc/libview-shot.so.p -Isrc -I../src -I/usr/include/cairo -I/usr/include/lzo -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/sysprof-4 -I/usr/include/pixman-1 -I/usr/include/pango-1.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/fribidi -I/usr/include/libdrm -I/usr/include/libevdev-1.0 -I/usr/include/libxml2 -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -std=c++17 -O3 -DWLR_USE_UNSTABLE -DWAYFIRE_PLUGIN -Wno-unused-parameter -fPIC -pthread -MD -MQ src/libview-shot.so.p/view-shot.cpp.o -MF src/libview-shot.so.p/view-shot.cpp.o.d -o src/libview-shot.so.p/view-shot.cpp.o -c ../src/view-shot.cpp
../src/view-shot.cpp: In instantiation of ‘wayfire_view_shot::<lambda(auto:1)> [with auto:1 = wf::activator_data_t]’:
/usr/include/c++/12.2.0/type_traits:2565:26:   required by substitution of ‘template<class _Fn, class ... _Args> static std::__result_of_success<decltype (declval<_Fn>()((declval<_Args>)()...)), std::__invoke_other> std::__result_of_other_impl::_S_test(int) [with _Fn = wayfire_view_shot::<lambda(auto:1)>&; _Args = {const wf::activator_data_t&}]’
/usr/include/c++/12.2.0/type_traits:2576:55:   required from  struct std::__result_of_impl<false, false, wayfire_view_shot::<lambda(auto:1)>&, const wf::activator_data_t&>’
/usr/include/c++/12.2.0/bits/std_function.h:348:9:   recursively required by substitution of ‘template<class _Result, class _Ret> struct std::__is_invocable_impl<_Result, _Ret, false, std::__void_t<typename _CTp::type> > [with _Result = std::__invoke_result<wayfire_view_shot::<lambda(auto:1)>&, const wf::activator_data_t&>; _Ret = bool]’
/usr/include/c++/12.2.0/bits/std_function.h:348:9:   required from ‘struct std::function<bool(const wf::activator_data_t&)>::_Callable<wayfire_view_shot::<lambda(auto:1)>, wayfire_view_shot::<lambda(auto:1)>, std::__invoke_result<wayfire_view_shot::<lambda(auto:1)>&, const wf::activator_data_t&> >’
/usr/include/c++/12.2.0/bits/std_function.h:353:8:   required by substitution of ‘template<class _Res, class ... _ArgTypes> template<class _Cond, class _Tp> using _Requires = std::__enable_if_t<_Cond::value, _Tp> [with _Cond = std::function<bool(const wf::activator_data_t&)>::_Callable<wayfire_view_shot::<lambda(auto:1)>, wayfire_view_shot::<lambda(auto:1)>, std::__invoke_result<wayfire_view_shot::<lambda(auto:1)>&, const wf::activator_data_t&> >; _Tp = void; _Res = bool; _ArgTypes = {const wf::activator_data_t&}]’
/usr/include/c++/12.2.0/bits/std_function.h:434:9:   required by substitution of ‘template<class _Functor, class _Constraints> std::function<bool(const wf::activator_data_t&)>::function(_Functor&&) [with _Functor = wayfire_view_shot::<lambda(auto:1)>; _Constraints = <missing>]’
../src/view-shot.cpp:107:5:   required from here
../src/view-shot.cpp:77:72: error: invalid initialization of reference of type ‘const wf::framebuffer_t&’ from expression of type ‘void’
   77 |         const wf::framebuffer_t& offscreen_buffer = view->take_snapshot();
      |                                                     ~~~~~~~~~~~~~~~~~~~^~
[21/43] Compiling C++ object ...iio.so.p/autorotate-iio.cpp.o
ninja: build stopped: subcommand failed.
```

Currently using Artix LInux with Kernel 5.19-zen

**Comment by soreau** [comment]
This sounds like you are trying to build wayfire-plugins-extra master branch against wayfire 0.7.x. If this is the case, you will want to use the 0.7.x branch of wayfire-plugins-extra.

**Comment by Tryware** [comment]
> This sounds like you are trying to build wayfire-plugins-extra master branch against wayfire 0.7.x. If this is the case, you will want to use the 0.7.x branch of wayfire-plugins-extra.


Now, it returns me this

`
ninja: Entering directory `build'
[42/43] Compiling C++ object src/libview-shot.so.p/view-shot.cpp.o
FAILED: src/libview-shot.so.p/view-shot.cpp.o
ccache c++ -Isrc/libview-shot.so.p -Isrc -I../src -I/usr/include/cairo -I/usr/include/lzo -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/sysprof-4 -I/usr/include/pixman-1 -I/usr/include/pango-1.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/fribidi -I/usr/include/libdrm -I/usr/include/libevdev-1.0 -I/usr/include/libxml2 -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -std=c++17 -O3 -DWLR_USE_UNSTABLE -DWAYFIRE_PLUGIN -Wno-unused-parameter -fPIC -pthread -MD -MQ src/libview-shot.so.p/view-shot.cpp.o -MF src/libview-shot.so.p/view-shot.cpp.o.d -o src/libview-shot.so.p/view-shot.cpp.o -c ../src/view-shot.cpp
../src/view-shot.cpp: In instantiation of ‘wayfire_view_shot::<lambda(auto:1)> [with auto:1 = wf::activator_data_t]’:
/usr/include/c++/12.2.0/type_traits:2565:26:   required by substitution of ‘template<class _Fn, class ... _Args> static std::__result_of_success<decltype (declval<_Fn>()((declval<_Args>)()...)), std::__invoke_other> std::__result_of_other_impl::_S_test(int) [with _Fn = wayfire_view_shot::<lambda(auto:1)>&; _Args = {const wf::activator_data_t&}]’
/usr/include/c++/12.2.0/type_traits:2576:55:   required from ‘struct std::__result_of_impl<false, false, wayfire_view_shot::<lambda(auto:1)>&, const wf::activator_data_t&>’
/usr/include/c++/12.2.0/bits/std_function.h:348:9:   recursively required by substitution of ‘template<class _Result, class _Ret> struct std::__is_invocable_impl<_Result, _Ret, false, std::__void_t<typename _CTp::type> > [with _Result = std::__invoke_result<wayfire_view_shot::<lambda(auto:1)>&, const wf::activator_data_t&>; _Ret = bool]’
/usr/include/c++/12.2.0/bits/std_function.h:348:9:   required from ‘struct std::function<bool(const wf::activator_data_t&)>::_Callable<wayfire_view_shot::<lambda(auto:1)>, wayfire_view_shot::<lambda(auto:1)>, std::__invoke_result<wayfire_view_shot::<lambda(auto:1)>&, const wf::activator_data_t&> >’
/usr/include/c++/12.2.0/bits/std_function.h:353:8:   required by substitution of ‘template<class _Res, class ... _ArgTypes> template<class _Cond, class _Tp> using _Requires = std::__enable_if_t<_Cond::value, _Tp> [with _Cond = std::function<bool(const wf::activator_data_t&)>::_Callable<wayfire_view_shot::<lambda(auto:1)>, wayfire_view_shot::<lambda(auto:1)>, std::__invoke_result<wayfire_view_shot::<lambda(auto:1)>&, const wf::activator_data_t&> >; _Tp = void; _Res = bool; _ArgTypes = {const wf::activator_data_t&}]’
/usr/include/c++/12.2.0/bits/std_function.h:434:9:   required by substitution of ‘template<class _Functor, class _Constraints> std::function<bool(const wf::activator_data_t&)>::function(_Functor&&) [with _Functor = wayfire_view_shot::<lambda(auto:1)>; _Constraints = <missing>]’
../src/view-shot.cpp:107:5:   required from here
../src/view-shot.cpp:77:72: error: invalid initialization of reference of type ‘const wf::framebuffer_t&’ from expression of type ‘void’
   77 |         const wf::framebuffer_t& offscreen_buffer = view->take_snapshot();
      |                                                     ~~~~~~~~~~~~~~~~~~~^~
ninja: build stopped: subcommand failed.`

**Comment by soreau** [comment]
You are still using the master branch of wayfire-plugins-extra. When you are using 0.7.x, view-shot plugin isn't included at all.

**Comment by Tryware** [comment]
> h

![image](https://user-images.githubusercontent.com/82564850/193166610-711fc599-2bd9-4129-a4fb-0d7454a81b83.png)
This is the 0.7.X branch i compiled from

**Comment by Tryware** [comment]
Oh, i noticed my mistake. It was still compiling from the master branch, i'm sorry

**Comment by soreau** [comment]
If 0.7.x branch didn't build, please feel free to re-open the issue. Closing for now.
