### ISSUE TITLE
Any plan to update this repo to keep up with the latest wayfire core?

### ISSUE THREAD

**Issue by ssfdust** [WayfireWM/wayfire-plugins-extra#138]
Due to the break changes in wayfire core rencently, the repo can't be compiled any more with the latest wayfire core.

Do you have a plan to fix the problem?

**Comment by marcusbritanicus** [comment]
@ssfdust Work is under way to fix this. The changes are quite extensive, and hence the delay. @soreau is working on this.

If it helps you, you can [this patch](http://ix.io/4fcg). I have commented out the modules that do not compile with wayfire master.
(Run `curl http://ix.io/4fcg | git apply` to apply the patch)
