### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by DeadMozay** [WayfireWM/wayfire-plugins-extra#15]
How soon are you planning to release? I am building wayfire packages for openSUSE, only this package was left without release, without release they do not want to accept it in the repository

**Comment by soreau** [comment]
I think we could do a release with wayfire 0.5.0, what do you think @ammen99?

**Comment by ahesford** [comment]
What's the status of this request? We're interested in packaging this for Void Linux as well.

**Comment by soreau** [comment]
https://github.com/WayfireWM/wayfire-plugins-extra/releases/tag/v0.5.0
