### ISSUE TITLE
does not compile

### ISSUE THREAD

**Issue by UltraBlackLinux** [WayfireWM/wayfire-plugins-extra#158]
Hey there,
I just tried rebuilding wayfire-plugins-extra-git against my new wayfire version to see if it was causing issues and I got the following errors: 
[wf-git.log](https://github.com/WayfireWM/wayfire-plugins-extra/files/10342861/wf-git.log)

Is there anything you can do about that?
Thanks!

**Comment by soreau** [comment]
When I tested here, it looks like mag just needs porting to the new API. I will close this issue once the package builds again.
