### ISSUE TITLE
Rule: Do not steal focus on showing this window

### ISSUE THREAD

**Issue by tsujan** [WayfireWM/wayfire-plugins-extra#167]
Is it possible to implement such a rule? Or does it already exist (I have the stable version of Wayfire with some patches from git)?

Since apps can't control the activation of their windows under Wayland (without having Wayland codes), such a rule seems like a must to me, not less important than rules for positioning, making sticky, etc.

**Comment by tsujan** [comment]
> This should be simple enough to implement in a plugin.

Being in a plugin might not be consistent with the rules about stickiness and..., which you implemented inside Wayfire itself.

**Comment by soreau** [comment]
I think the idea is that core should do as little as possible while dispatching hooks for plugins to use. Also as @ammen99 said on IRC:

"<ammen99> I'd like to remove sticky as well, simply haven't found a good way to do it without breaking the workspace switching code "

**Comment by marcusbritanicus** [comment]
@tsujan Unlike the always on top or sticky rules, focus stealing prevention will be applied to all views. It will not make much sense to apply to one single view. I believe your use case would be something specific like password dialogs. But, since this plugin will apply the rules to all views, all the specific cases will also be covered. 

If you want a view that grabs all input events, then setting a window-rule would be a poor choice of technique. It would be much better to use wlr-input-inhibitor.

**Comment by tsujan** [comment]
No, my feature request was about something totally different, as its title says. @Vladimir-csp's comment was quite natural and valid but very different.

**Comment by marcusbritanicus** [comment]
As I said, since [focus-stealing prevention plugin](#168) will be soon available, there does not seem to be any reason to have this specific rule.

**Comment by tsujan** [comment]
Since you might ask about a use case:

We don't want to add Wayland-specific codes to our Qt apps for positioning them or making them sticky. Most Wayland compositors provide rules for those properties. Similarly, we can't add Wayland-specific codes to `lxqt-notificationd`to prevent its popup from stealing focus. Hence the need for a rule.

You might also ask, "Why can't you add Wayland-specific codes?" The answer is that we want our apps to be agnostic toward Wayland compositors/WM, as they are toward X11 WMs.

**Comment by soreau** [comment]
Why can't such functionality be implemented in the proposed plugin?

**Comment by tsujan** [comment]
> Why can't such functionality be implemented in the proposed plugin?

I can, and what you described at https://github.com/WayfireWM/wayfire-plugins-extra/issues/167#issuecomment-1438105281 was really good. It just wasn't what I'd requested.

**Comment by marcusbritanicus** [comment]
@tsujan I would say, LXQt desktop components is a very special case. @soreau might disagree, but I would say it does not merit a special rule. 

However, since I called it a special case, I'd dare say it requires a special consideration as well. I'm working on a new protocol for Wayfire to implement desktop components. A [draft version](https://gitlab.com/wayfireplugins/desq-shell) is online. An off-shot of that plugin will allow you to integrate LXQt components in Wayfire. I am planning to write such a plugin, perhaps you can help me develop it by contributing ideas and/or code. It would benefit not only LXQt, but also other DEs.

**Comment by soreau** [comment]
@tsujan I wrote [this patch](http://ix.io/4oRp) but it's untested. It applies on top of the proposed plugin branch. If you can test and say if it works, I'll apply it.

**Comment by marcusbritanicus** [comment]
> You might also ask, "Why can't you add Wayland-specific codes?" The answer is that we want our apps to be agnostic toward Wayland compositors/WMs, as they are toward X11 WMs.

Special cases require survival consideration as well. Your apps (more appropriately, LXQt Desktop Components) are not X11 agnostic. They specifically cater to X11 _through Qt_. Window flags which you set in Qt (above/below/bypass-wm, etc) are X11 specific. Since Wayland doesn't support such features, your left to wonder what to do. 

That said, it's easy to add Wayland specific code to your DE components, and yet have them work on X11. Just guard the Wayland specific code in a `if (...) {}`  statement. You may want to have a look at [WayQt](https://gitlab.com/desktop-frameworks/wayqt) which provides ready access to Wayland protocols.

**Comment by soreau** [comment]
@tsujan After @marcusbritanicus explained more what you mean, I think [this patch](http://ix.io/4oRw) is more in line with what you want.

**Comment by tsujan** [comment]
@soreau

Thanks for caring! I was going to add a comment, but you were faster :) Yes, the description of your new patch is exactly what I meant. I'm applying and testing it now...

**Comment by marcusbritanicus** [comment]
@tsujan I was also trying soreau's patch for lxqt-notificationd. It does not show any notificaitons at all (with or without that patch) when run as native client. Something I should be aware of? On the other hand running it as xwayland client (`lxqt-notificationd -platform xcb`) shows proper notifications, and soreau's patch isn't needed, AFAIU.

**Comment by tsujan** [comment]
@soreau
You patch ("If a view matches when mapped, focus is reset to the last view with focus") works as intended. Thanks again!

@marcusbritanicus
`lxqt-notificationd` runs under Wayland here:

```
$ wf-info
=========================
View ID: 30
Client PID: 326149
Workspace: 0,0
App ID: lxqt-notificationd
Title: lxqt-notificationd
Role: TOPLEVEL
Geometry: 0,34 300x100
Xwayland: false
Focused: false
=========================
```
I tested the patch with this rule:

```
[focus-steal-prevent]

deny_focus_views = app_id is "lxqt-notificationd"
```

**Comment by tsujan** [comment]
> Your apps (more appropriately, LXQt Desktop Components) are not X11 agnostic.

@marcusbritanicus, I didn't say that; I said they are agnostic toward X11 **WMs**. Similarly, being limited to a specific (group of) Wayland compositors/WMs isn't an option. Rules like `deny_focus_views` are a great help.

**Comment by marcusbritanicus** [comment]
@tsujan It is fair to say that, even though I do not agree with you completely. I would not like to spam this issue discussing LXQt. Do let me know if you're on matrix/irc or other way I can chat with you.

I would love to see LXQt running natively on wayland !

**Comment by tsujan** [comment]
@marcusbritanicus 
Your comments were quite relevant. But, yes, let's not limit this page to LXQt. Thanks!

> I would love to see LXQt running natively on wayland !

I use pcmanfm-qt (in the daemon mode), lxqt-notificationd, lxqt-policykit-agent, lxqt-qtplugin, libqtxdg and some other LXQt components under the stable version of Wayfire + a few patches (@stefonarch tests more LXQt components under well-known Wayland compositors, including Wayfire). I've used Wayfire to find and fix Wayland-specific problems in Qt apps *without Wayland-specific codes* — and, by Qt apps, I don't mean only LXQt apps. Until now, Wayfire has been the most comfortable Wayland session for me.

**Comment by stefonarch** [comment]
I tested now this plugin, but what happens here is quite inconvenient:

* polkit authentication window (for example with `ninja -C build/ install`) opens behind terminal window
* same for links clicked, firefox in background

**Comment by marcusbritanicus** [comment]
@stefonarch I believe you can make a window rule for polkit window to make it always on top. 

The entire point of focus stealing prevention is so that newly opened windows don't steal focus from the current window the user in interacting with - you can see the same behaviour in KDE Plasma as well (X11 and Wayland). If you open a file from file manager, the app that opens the file will open in the background.

In wayfire, when a newly created view is not given focus, wayfire emits a view-hints signal, which indicates that a view is demanding attention. You can use the [dbusqt](https://gitlab.com/wayfireplugins/dbusqt) get this info and highlight your taskbar entry, or give it focus.

**Comment by stefonarch** [comment]
Plasma does like that?  Will have a look, I hardly use it.

But this is  only complicating simple things for me, I like to have as little rules as possible. At first read I understood that it disables focus stealing while typing, probably I've overseen (or it wasn't there at the beginning) the "pointer click".

> A timer will be reset to the timeout (in ms) on every keystroke and pointer click

**Comment by tsujan** [comment]
All instances of focus stealing prevention I've seen in the X11 world have a setting for their intensity. The timer of the current implementation doesn't seem to work in that way — although it's a good idea (similar to touchpad disabling while typing).

Of course, the user wants to see a video file by clicking in the file manager or run an app from a terminal emulator by pressing ENTER, while he may or may not want to focus Firefox *in another workspace* when he opens a link. The degree of FSP handles this.

**Comment by soreau** [comment]
@stefonarch @tsujan Thank you both for testing this. In light of the issues that seem to be about clicking, I wonder if this behavior makes sense: Ignore clicks for focus stealing prevention unless the keyboard timer is active. This way, you could still switch focus by clicking, and if the timer isn't active, it won't become active for clicks. Does this make sense? It's probably easier for me to implement and have y'all test than me trying to explain it.

**Comment by stefonarch** [comment]
Previously I had the patch and 
```
[focus-steal-prevent]
deny_focus_views = app_id is "lxqt-notificationd"
timeout = 0
```
in `wayfire.ini` and it worked fine for notifications and normal click behavior.
I cleaned this now and tested the new commit, but what I see is:

* polkit auth still behind (obvious, it's triggered by typing)
* any shortcut will open the relative app in background (obvious too)
* links are ok now, file opening too

I think an simple approach like in Hyprland (`windowrule=nofocus,app_id`or sway (`no_focus [app_id="xyz"]`) would be much more convenient for all uses I can see.

>you can see the same behaviour in KDE Plasma as well (X11 and Wayland). If you open a file from file manager, the app that opens the file will open in the background.

I had a look, I can't see this in plasma - any image or video opens in foreground when clicked in the FM

**Comment by soreau** [comment]
> Previously I had the patch and
> 
> ```
> [focus-steal-prevent]
> deny_focus_views = app_id is "lxqt-notificationd"
> timeout = 0
> ```

I was about to say, a timeout of 0 should disable input-activated focus stealing prevention altogether.

> I think an simple approach like in Hyprland (windowrule=nofocus,app_id) or sway (no_focus [app_id="xyz"]) would be more convenient for the uses I can see.

Can you explain how these behaviors are different than the plugin `deny_focus_views` option?

**Comment by stefonarch** [comment]
> I was about to say, a timeout of 0 should disable input-activated focus stealing prevention altogether.

Yes, but  this is the same as just not using it at all, no (except the patch for `deny_focus_views = app_id is ""`)?


> Can you explain how these behaviors are different than the plugin `deny_focus_views` option?

Those exclude just one or more specific apps from focus stealing always, I can't see for me why I should generally deny any focus stealing while typing which could make sense typing in a text field but not when it's a shortcut or a command that triggers a GUI.

**Comment by soreau** [comment]
> > I was about to say, a timeout of 0 should disable input-activated focus stealing prevention altogether.
> 
> Yes, but this is the same as just not using it at all, no (except the patch for `deny_focus_views = app_id is ""`)?

Correct.

> 
> > Can you explain how these behaviors are different than the plugin `deny_focus_views` option?
> 
> Those exclude just one or more specific apps from focus stealing always, I can't see for me why I should generally deny any focus stealing while typing which could make sense typing in a text field but not when it's a shortcut or a command that triggers a GUI.

When you say shortcut here, I assume you mean a wayfire key binding? So far as running commands, perhaps focus stealing prevention should be canceled when `KEY_ENTER` is pressed?

**Comment by marcusbritanicus** [comment]
@stefonarch I'm not sure how you'll differentiate between a text field and say, pressing enter in a file manager. They both have keyboard focus. Technically, focus stealing prevention means do not give focus to views when user is interacting with another view. So when you hit enter on a file manager, you're actually interacting with it. 

I do understand @tsujan  and your point... The user would prefer that double clicking on a file to open a file and waiting would bring up the app that opens the file.

@soreau I think I might have a more generic solution for this.  Perhaps, we can try and remember the views that were denied focus. When the timeout is reached, and the user has not interacted with the current view, then probably we could automatically focus that lat view that was denied focus - as far as that view opens in the current output and workspace. That would solve most problems, I think.

**Comment by stefonarch** [comment]
> When you say shortcut here, I assume you mean a wayfire key binding? So far as running commands, perhaps focus stealing prevention should be canceled when `KEY_ENTER` is pressed?

I avoid using too many shortcuts as applications opened by those won't be closed gently because the're outside of  `lxqt-session`. But some I do use (terminal, filemanager) and keys are all `<super> + KEY_*` but users could use any modifier, so maybe excluding all could be an option.

**Comment by soreau** [comment]
@tsujan @stefonarch I have made it to where focus stealing prevention is canceled on binding handled and KEY_ENTER. This is a first draft of this behavior, but it also requires patching wayfire. [wayfire patch](http://ix.io/4oVt) [focus-steal-prevent patch](http://ix.io/4oVv).

**Comment by tsujan** [comment]
Not intending to rain on anyone's parade, I think that focus stealing prevention (FSP) doesn't make sense under Wayland (and I emphasize again that my report wasn't about FSP).

Under X11, apps can activate and/or raise their windows. That's why FSP is needed. For example, my browser is on another virtual desktop, while I click a link. Without FSP, the virtual desktop will switch to that of the browser because the browser activates its window (in its code). That won't happen with FSP: the WM won't let the virtual desktop change; instead, it'll put the taskbar item of the browser in a state of "urgency" (and the taskbar implementation might change its background color).

Under Wayland, apps can't activate their windows; window activation is at the mercy of the WM. Therefore, FSP doesn't make much sense.

On the other hand, having a rule for denying focus makes perfect sense under Wayland, because apps can't do it themselves. A Wayland compositor may have codes for denying focus appropriately, or it can have a rule for it, or both.

In contrast, under X11, apps are able show their windows without "activating" them (= giving them the focus). Therefore, the above-mentioned rule isn't needed there.

**Comment by soreau** [comment]
@tsujan To me, it seems you can achieve what you want by setting FSP plugin timeout to 0, to disable any input-activated FSP and just use the deny-focus-views match part. But apparently you are not liking this because the code live in the FSP plugin and not window rules? If you know all the details of how it should work and where the code should live, why not write your own patch and/or make a pull request?

**Comment by tsujan** [comment]
> But apparently you are not liking this because the code live in the FSP plugin and not window rules? 

I don't dislike it. My previous comment was about FSP in general; I thought it was pertinent to the discussion.

> why not write your own patch and/or make a pull request?

I made a small and hasty patch for my personal use, until the features are implemented in Wayfire. It isn't good for a PR but adds `no_focus` and `no_raise` under `[core]`. Having a usable desktop (in contrast to a mere background) is only possible with something like `no_raise` — it allowed me to use pcmanfm-qt's desktop under Wayfire.

**Comment by stefonarch** [comment]
Patching wayfire ok, plugins-extra + patch fails:
```

[44/45] Compiling C++ object src/libfocus-steal-prevent.so.p/focus-steal-prevent.cpp.o
FAILED: src/libfocus-steal-prevent.so.p/focus-steal-prevent.cpp.o 
ccache c++ -Isrc/libfocus-steal-prevent.so.p -Isrc -I../src -I/usr/include/cairo -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/sysprof-4 -I/usr/include/pixman-1 -I/usr/include/pango-1.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/fribidi -I/usr/include/libdrm -I/usr/include/libevdev-1.0 -I/usr/include/libxml2 -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -std=c++17 -O0 -g -DWLR_USE_UNSTABLE -DWAYFIRE_PLUGIN -Wno-unused-parameter -fPIC -pthread -MD -MQ src/libfocus-steal-prevent.so.p/focus-steal-prevent.cpp.o -MF src/libfocus-steal-prevent.so.p/focus-steal-prevent.cpp.o.d -o src/libfocus-steal-prevent.so.p/focus-steal-prevent.cpp.o -c ../src/focus-steal-prevent.cpp
../src/focus-steal-prevent.cpp: In lambda function:
../src/focus-steal-prevent.cpp:69:17: error: ‘struct wf::post_input_event_signal<wlr_keyboard_key_event>’ has no member named ‘handled’
   69 |         if (ev->handled || ev->event->keycode == KEY_ENTER)
      |                 ^~~~~~~
ninja: build stopped: subcommand failed.

```

**Comment by stefonarch** [comment]
Ok, removed obsolete stuff in `/usr/local/` and it works all fine as I see:

* `<application> <file>` in terminal works
* `lxqt-notificationd` windows don't steal focus
* shortcuts open apps

**Comment by stefonarch** [comment]
Found now that `Ctrl+s` after editing system files opens the polkit window in background, which shouldn't happen.
