### ISSUE TITLE
Background-view doesn't promise what it's name says

### ISSUE THREAD

**Issue by stefonarch** [WayfireWM/wayfire-plugins-extra#171]
The plugins name induces that an application can be shown in background, not closable, without decorations, not shown in scale and so on, but I didn't manage to show anything else than `mpv` and here DND from thunar or pcmanfm-qt do not work.

```
[background-view]
command = strawberry
app_id = strawberry

```
Tested also with lximage-qt, pcmanfm-qt, vlc, thunar and maybe some others -   a normal toplevel window is always opened at session start.

As it shows mpv it should at least show others too.

**Comment by marcusbritanicus** [comment]
@stefonarch It is rather str
![2023-02-25_00:01:56](https://user-images.githubusercontent.com/3350667/221262233-19283625-3932-4901-8371-2c8d3710dcdb.png)
ange that you're unable to use lximage-qt with background-view. I tried here with `lximage-qt`, `lximage-qt --fullscreen`, `qteye` and `desq-eye` apps. All the said apps work perfectly. Here is a screenshot of `lximage-qt` with menu and toolbar. The panel and the widgets on the right are layer shell surfaces (TOP and BOTTOM layers, respectively.) 

My settings for `background-view`:
```
background-view: {
    app-id: lximage-qt
    command: lximage-qt
    file: /home/cosmos/.cache/DesQ/background-eDP-1.jpg
}
```

FYI, I'm using wayfire 0.8.0-a1f57570 (Feb 15 2023, branch 'master'). No patches.

**Comment by stefonarch** [comment]
Ok, thanks, found the difference: ` app_id` - I was obviously used to the underscore, but it's not conform to the rest of` wayfire.ini`. So I don't close it also if it's solved.

**Comment by stefonarch** [comment]
Maybe too:

```
<_short>Application Identifier</_short>
<_long>Has to match application</_long>
```
