### ISSUE TITLE
getting build error

### ISSUE THREAD

**Issue by mrsteve0924** [WayfireWM/wayfire-plugins-extra#178]
![20230602_02h14m27s_grim](https://github.com/WayfireWM/wayfire-plugins-extra/assets/37476191/ce1ca809-a563-4cfa-8e0c-7c9a40d4f274)

**Comment by mrsteve0924** [comment]
i updated to latest commit on wayfire but now I get a different build error.

is it strange that there are several `#include <wayfire/workspace-manager.hpp>` references but no file?

`root@wayland ~/wayfire-plugins-extra # ninja -C build
ninja: Entering directory `build'
[2/35] Compiling C++ object src/libfollow-focus.so.p/follow-focus.cpp.o
FAILED: src/libfollow-focus.so.p/follow-focus.cpp.o 
c++ -Isrc/libfollow-focus.so.p -Isrc -I../src -I/usr/include/cairo -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/sysprof-4 -I/usr/include/pixman-1 -I/usr/include/pango-1.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/fribidi -I/usr/include/libdrm -I/usr/include/libevdev-1.0 -I/usr/include/libxml2 -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -std=c++17 -O0 -g -DWLR_USE_UNSTABLE -DWAYFIRE_PLUGIN -Wno-unused-parameter -fPIC -pthread -MD -MQ src/libfollow-focus.so.p/follow-focus.cpp.o -MF src/libfollow-focus.so.p/follow-focus.cpp.o.d -o src/libfollow-focus.so.p/follow-focus.cpp.o -c ../src/follow-focus.cpp
../src/follow-focus.cpp:29:10: fatal error: wayfire/workspace-manager.hpp: No such file or directory
   29 | #include <wayfire/workspace-manager.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
[3/35] Compiling C++ object src/libbackground-view.so.p/background-view.cpp.o
FAILED: src/libbackground-view.so.p/background-view.cpp.o 
c++ -Isrc/libbackground-view.so.p -Isrc -I../src -I/usr/include/cairo -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/sysprof-4 -I/usr/include/pixman-1 -I/usr/include/pango-1.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/fribidi -I/usr/include/libdrm -I/usr/include/libevdev-1.0 -I/usr/include/libxml2 -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -std=c++17 -O0 -g -DWLR_USE_UNSTABLE -DWAYFIRE_PLUGIN -Wno-unused-parameter -fPIC -pthread -MD -MQ src/libbackground-view.so.p/background-view.cpp.o -MF src/libbackground-view.so.p/background-view.cpp.o.d -o src/libbackground-view.so.p/background-view.cpp.o -c ../src/background-view.cpp
../src/background-view.cpp:31:10: fatal error: wayfire/workspace-manager.hpp: No such file or directory
   31 | #include <wayfire/workspace-manager.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
[6/35] Compiling C++ object src/libbench.so.p/bench.cpp.o
FAILED: src/libbench.so.p/bench.cpp.o 
c++ -Isrc/libbench.so.p -Isrc -I../src -I/usr/include/cairo -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/sysprof-4 -I/usr/include/pixman-1 -I/usr/include/pango-1.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/fribidi -I/usr/include/libdrm -I/usr/include/libevdev-1.0 -I/usr/include/libxml2 -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -std=c++17 -O0 -g -DWLR_USE_UNSTABLE -DWAYFIRE_PLUGIN -Wno-unused-parameter -fPIC -pthread -MD -MQ src/libbench.so.p/bench.cpp.o -MF src/libbench.so.p/bench.cpp.o.d -o src/libbench.so.p/bench.cpp.o -c ../src/bench.cpp
../src/bench.cpp:32:10: fatal error: wayfire/workspace-manager.hpp: No such file or directory
   32 | #include <wayfire/workspace-manager.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
[7/35] Compiling C++ object src/libforce-fullscreen.so.p/force-fullscreen.cpp.o
FAILED: src/libforce-fullscreen.so.p/force-fullscreen.cpp.o 
c++ -Isrc/libforce-fullscreen.so.p -Isrc -I../src -I/usr/include/cairo -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/sysprof-4 -I/usr/include/pixman-1 -I/usr/include/pango-1.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/fribidi -I/usr/include/libdrm -I/usr/include/libevdev-1.0 -I/usr/include/libxml2 -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -std=c++17 -O0 -g -DWLR_USE_UNSTABLE -DWAYFIRE_PLUGIN -Wno-unused-parameter -fPIC -pthread -MD -MQ src/libforce-fullscreen.so.p/force-fullscreen.cpp.o -MF src/libforce-fullscreen.so.p/force-fullscreen.cpp.o.d -o src/libforce-fullscreen.so.p/force-fullscreen.cpp.o -c ../src/force-fullscreen.cpp
../src/force-fullscreen.cpp:32:10: fatal error: wayfire/workspace-manager.hpp: No such file or directory
   32 | #include <wayfire/workspace-manager.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
[8/35] Compiling C++ object src/libannotate.so.p/annotate.cpp.o
FAILED: src/libannotate.so.p/annotate.cpp.o 
c++ -Isrc/libannotate.so.p -Isrc -I../src -I/usr/include/cairo -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/sysprof-4 -I/usr/include/pixman-1 -I/usr/include/pango-1.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/fribidi -I/usr/include/libdrm -I/usr/include/libevdev-1.0 -I/usr/include/libxml2 -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -std=c++17 -O0 -g -DWLR_USE_UNSTABLE -DWAYFIRE_PLUGIN -Wno-unused-parameter -fPIC -pthread -MD -MQ src/libannotate.so.p/annotate.cpp.o -MF src/libannotate.so.p/annotate.cpp.o.d -o src/libannotate.so.p/annotate.cpp.o -c ../src/annotate.cpp
../src/annotate.cpp:39:10: fatal error: wayfire/workspace-manager.hpp: No such file or directory
   39 | #include "wayfire/workspace-manager.hpp"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
[9/35] Compiling C++ object src/libfocus-steal-prevent.so.p/focus-steal-prevent.cpp.o
FAILED: src/libfocus-steal-prevent.so.p/focus-steal-prevent.cpp.o 
c++ -Isrc/libfocus-steal-prevent.so.p -Isrc -I../src -I/usr/include/cairo -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/sysprof-4 -I/usr/include/pixman-1 -I/usr/include/pango-1.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/fribidi -I/usr/include/libdrm -I/usr/include/libevdev-1.0 -I/usr/include/libxml2 -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -std=c++17 -O0 -g -DWLR_USE_UNSTABLE -DWAYFIRE_PLUGIN -Wno-unused-parameter -fPIC -pthread -MD -MQ src/libfocus-steal-prevent.so.p/focus-steal-prevent.cpp.o -MF src/libfocus-steal-prevent.so.p/focus-steal-prevent.cpp.o.d -o src/libfocus-steal-prevent.so.p/focus-steal-prevent.cpp.o -c ../src/focus-steal-prevent.cpp
../src/focus-steal-prevent.cpp:24:10: fatal error: wayfire/workspace-manager.hpp: No such file or directory
   24 | #include <wayfire/workspace-manager.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
[10/35] Compiling C++ object src/libhide-cursor.so.p/hide-cursor.cpp.o
FAILED: src/libhide-cursor.so.p/hide-cursor.cpp.o 
c++ -Isrc/libhide-cursor.so.p -Isrc -I../src -I/usr/include/cairo -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/sysprof-4 -I/usr/include/pixman-1 -I/usr/include/pango-1.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/fribidi -I/usr/include/libdrm -I/usr/include/libevdev-1.0 -I/usr/include/libxml2 -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -std=c++17 -O0 -g -DWLR_USE_UNSTABLE -DWAYFIRE_PLUGIN -Wno-unused-parameter -fPIC -pthread -MD -MQ src/libhide-cursor.so.p/hide-cursor.cpp.o -MF src/libhide-cursor.so.p/hide-cursor.cpp.o.d -o src/libhide-cursor.so.p/hide-cursor.cpp.o -c ../src/hide-cursor.cpp
../src/hide-cursor.cpp:36:5: error: invalid use of template-name ‘wf::wl_timer’ without an argument list
   36 |     wf::wl_timer hide_timer;
      |     ^~
[11/35] Compiling C++ object src/libjoin-views.so.p/join-views.cpp.o
ninja: build stopped: subcommand failed.
`

**Comment by ssfdust** [comment]
@soreau It seems that the last major commit has been merged in wayfire core. Would you please track the update with the latest wayfire core?

**Comment by ammen99** [comment]
Most plugins except background-view and force-fullscreen have been now updated.

**Comment by mrsteve0924** [comment]
hey very excited to this update.  but couldnt get it to build.  i do have latest wayfire and wf-config.  anything else i can try?

ninja: Entering directory `build'
[6/7] Compiling C++ object src/libmag.so.p/mag.cpp.o
FAILED: src/libmag.so.p/mag.cpp.o 
c++ -Isrc/libmag.so.p -Isrc -I../src -I/usr/include/cairo -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/sysprof-4 -I/usr/include/pixman-1 -I/usr/include/pango-1.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/fribidi -I/usr/include/libdrm -I/usr/include/libevdev-1.0 -I/usr/include/libxml2 -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -std=c++17 -O0 -g -DWLR_USE_UNSTABLE -DWAYFIRE_PLUGIN -Wno-unused-parameter -fPIC -pthread -MD -MQ src/libmag.so.p/mag.cpp.o -MF src/libmag.so.p/mag.cpp.o.d -o src/libmag.so.p/mag.cpp.o -c ../src/mag.cpp
../src/mag.cpp:44:10: fatal error: wayfire/nonstd/tracking-allocator.hpp: No such file or directory
   44 | #include <wayfire/nonstd/tracking-allocator.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.

**Comment by mrsteve0924** [comment]
follow-focus isn't working like i expected.  i assumed this plugin makes the focus follow the cursor.   did i assume correctly?
