### ISSUE TITLE
meson.build line 26 there is no proto subdir

### ISSUE THREAD

**Issue by librewish** [WayfireWM/wayfire-plugins-extra#2]

**Comment by librewish** [comment]
fix the meson.build i cant build the wayfire-extra-plugins package using pkgbuild

to make arch package

**Comment by librewish** [comment]
@ammen99 can you fix the meson.build file.
i want to add it to aur

**Comment by ammen99** [comment]
I had forgotten to include the `proto` directory, but it should be good now. Thanks for the reminder!
