### ISSUE TITLE
getting build error with latest commits

### ISSUE THREAD

**Issue by mrsteve0924** [WayfireWM/wayfire-plugins-extra#211]
tried building today and getting these errors.  i have latest wayfire and wlroots 17.0-1

ninja: Entering directory `build'
[2/6] Compiling C++ object src/libbench.so.p/bench.cpp.o
FAILED: src/libbench.so.p/bench.cpp.o 
c++ -Isrc/libbench.so.p -Isrc -I../src -I/usr/include/cairo -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/sysprof-6 -I/usr/include/pixman-1 -I/usr/include/pango-1.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/fribidi -I/usr/include/libdrm -I/usr/include/libevdev-1.0 -I/usr/include/libxml2 -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -std=c++17 -O0 -g -DWLR_USE_UNSTABLE -DWAYFIRE_PLUGIN -Wno-unused-parameter -fPIC -pthread -MD -MQ src/libbench.so.p/bench.cpp.o -MF src/libbench.so.p/bench.cpp.o.d -o src/libbench.so.p/bench.cpp.o -c ../src/bench.cpp
../src/bench.cpp: In lambda function:
../src/bench.cpp:297:31: error: no matching function for call to ‘wf::render_manager::damage(wf::geometry_t&, bool)’
  297 |         output->render->damage(cairo_geometry, false);
      |         ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~
In file included from ../src/bench.cpp:31:
/usr/include/wayfire/render-manager.hpp:152:10: note: candidate: ‘void wf::render_manager::damage(const wlr_box&)’
  152 |     void damage(const wlr_box& box);
      |          ^~~~~~
/usr/include/wayfire/render-manager.hpp:152:10: note:   candidate expects 1 argument, 2 provided
/usr/include/wayfire/render-manager.hpp:160:10: note: candidate: ‘void wf::render_manager::damage(const wf::region_t&)’
  160 |     void damage(const wf::region_t& region);
      |          ^~~~~~
/usr/include/wayfire/render-manager.hpp:160:10: note:   candidate expects 1 argument, 2 provided
[3/6] Compiling C++ object src/libbackground-view.so.p/background-view.cpp.o
FAILED: src/libbackground-view.so.p/background-view.cpp.o 
c++ -Isrc/libbackground-view.so.p -Isrc -I../src -I/usr/include/cairo -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/sysprof-6 -I/usr/include/pixman-1 -I/usr/include/pango-1.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/fribidi -I/usr/include/libdrm -I/usr/include/libevdev-1.0 -I/usr/include/libxml2 -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -std=c++17 -O0 -g -DWLR_USE_UNSTABLE -DWAYFIRE_PLUGIN -Wno-unused-parameter -fPIC -pthread -MD -MQ src/libbackground-view.so.p/background-view.cpp.o -MF src/libbackground-view.so.p/background-view.cpp.o.d -o src/libbackground-view.so.p/background-view.cpp.o -c ../src/background-view.cpp
../src/background-view.cpp: In lambda function:
../src/background-view.cpp:393:50: error: ‘wlr_xwayland_surface_try_from_wlr_surface’ was not declared in this scope; did you mean ‘wlr_xwayland_surface_from_wlr_surface’?
  393 |         wlr_xwayland_surface *xwayland_surface = wlr_xwayland_surface_try_from_wlr_surface(wlr_surface);
      |                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                  wlr_xwayland_surface_from_wlr_surface
../src/background-view.cpp: In member function ‘void wayfire_background_view::set_view_for_output(wayfire_toplevel_view, wlr_surface*, wf::output_t*)’:
../src/background-view.cpp:338:37: error: ‘wlr_xdg_surface_try_from_wlr_surface’ was not declared in this scope; did you mean ‘wlr_xdg_surface_from_wlr_surface’?
  338 |         if (wlr_xdg_surface *surf = wlr_xdg_surface_try_from_wlr_surface(surface))
      |                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                     wlr_xdg_surface_from_wlr_surface
../src/background-view.cpp:343:73: error: ‘struct wlr_surface::<unnamed>’ has no member named ‘unmap’
  343 |             new_view->on_unmap.connect(&toplevel->base->surface->events.unmap);
      |                                                                         ^~~~~
../src/background-view.cpp:347:47: error: ‘wlr_xwayland_surface_try_from_wlr_surface’ was not declared in this scope; did you mean ‘wlr_xwayland_surface_from_wlr_surface’?
  347 |         else if (wlr_xwayland_surface *surf = wlr_xwayland_surface_try_from_wlr_surface(surface))
      |                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                               wlr_xwayland_surface_from_wlr_surface
../src/background-view.cpp:352:63: error: ‘struct wlr_surface::<unnamed>’ has no member named ‘unmap’
  352 |             new_view->on_unmap.connect(&surf->surface->events.unmap);
      |                                                               ^~~~~
ninja: build stopped: subcommand failed.

**Comment by soreau** [comment]
Can you say what version of wayfire-plugins-extra you have? It seems like you are missing latest commits.

**Comment by mrsteve0924** [comment]
im on main branch from nov 25
![2023-11-26_20:17:49](https://github.com/WayfireWM/wayfire-plugins-extra/assets/37476191/f909aa1b-509c-4129-b2cf-c363861c42b2)

**Comment by soreau** [comment]
If you have latest wayfire *release* and not from git master, you will also need the latest *release* of wayfire-plugins-extra (and not git master).

**Comment by mrsteve0924** [comment]
i thought i had latest wayfire master but looks like things are getting updated fast.  i re-cloned latest master branch of wayfire, but it failed during rebuild.  Looks to me like it couldnt find my installed versions of wlroots 17 and wf-config.  I ended  up uninstalling those and rebuilding wayfire with the wlroots and wfconfig subprojects enabled.  finally built and running.  

Now trying to rebuild wayfire-plugins-extra and still getting errors.  build output here....
https://dpaste.com//A9WRFW6V6

**Comment by soreau** [comment]
> Now trying to rebuild wayfire-plugins-extra and still getting errors. build output here.... https://dpaste.com//A9WRFW6V6

The first thing I see is this:
```
/usr/local/include/wlr/render/drm_format_set.h:17:18: error: flexible array member ‘wlr_drm_format::modifiers’ not at end of ‘struct wlr_swapchain’
   17 |         uint64_t modifiers[];
      |                  ^~~~~~~~~
/usr/include/wlr/render/swapchain.h:24:35: note: next member ‘wlr_swapchain_slot wlr_swapchain::slots [4]’ declared here
```
Which means you likely have installations in /usr/ and /usr/local/. I would recommend uninstalling wlroots (and anything else wayfire related) from /usr/local/, then try again.

**Comment by mrsteve0924** [comment]
hmm. not sure how that would happen. i dont manually install anything wayfire related there.  i'll take a look. thanks

**Comment by soreau** [comment]
> EDIT: that worked. wpe now builds.

Great, glad you got it working!
