### ISSUE TITLE
Hinge plugin

### ISSUE THREAD

**Issue by milankozlovic** [WayfireWM/wayfire-plugins-extra#229]
I cloned and compiled the latest version of "wayfire-plugins-extra" from Wayfire Git Hub. I need a follow-focus plugin. Of course, I also activated most of the other plugins for testing purposes. Through Wcm, I tried various plugins, turned off the ones I didn't need, and experimented with the rest. I noticed that my fans are running at maximum power, and the processor temperature is over 90C. With Btop, I checked the processes that use the most CPU. Wayfire gathered the processor with 100% capacity all the time. Admittedly one of eight processors.

In Wcm, I turned off one plugin at a time, and if there were no changes, I would reactivate it. The primary winner was the "Hinge" plugin. When I turned it off, everything went back to normal. I checked the Core section in wayfire.ini, and that plugin was not even loaded. I inserted it into the list of plugins, and the moment I saved the file wayfire.ini, the temperature suddenly started to rise. I checked WCM, and this plugin was still not activated there. Of course, I deleted it from the list of plugins in the Core section, saved the wayfire.ini file, and everything calmed down again.

Description of "Hinge" plugin: "Given a filename, this plugin reads an int32 from it. This value should be in degrees, so from 0 to 360. Depending on the value, the keyboard and pointer inputs get disabled. - The name of the sensor device: /sys/bus/iio/devices/iio:device1/in_angl0_raw".

Settings in wayfire.ini:
[hinge]
filename = /sys/bus/iio/devices/iio:device1/in_angl0_raw
flip_degree = 180
poll_freq = 200
[probe.txt](https://github.com/WayfireWM/wayfire-plugins-extra/files/14300483/probe.txt)

**Comment by soreau** [comment]
Thank you for your detailed report. The extra plugins are not enabled by default and typically, people don't enable plugins that aren't needed. This is a special plugin only for devices that have the system file in question provided by some driver. If the angle changes are happening rapidly, or the file doesn't exist, this could be the culprit. There might be messages in the wayfire log (stdout of wayfire) when this is happening too. Were you needing a plugin like hinge that disables and enables the input, based on the laptop lid position? or were you just enabling all the plugins?

So far as wcm is concerned, it only reads wayfire.ini once on startup, so it doesn't show changes to the config file unless you restart wcm after saving.

**Comment by milankozlovic** [comment]
As mentioned, I tried different plugins to test and familiarize myself with their capabilities. I noticed an anomaly and tried to find the cause of the problem. I was curious because I have not encountered Hinge plugins before, and there is a setting for it in wayfire.ini. According to your answer and explanation, I won't need its functionality, but I'm glad I learned something. Thank you very much.

**Comment by soreau** [comment]
Not a problem. I'll see about looking at why it suffers from high resource usage with default settings. I'm guessing when the system file in question doesn't exist on the system, the problem happens. Perhaps we can print a warning or error message if the file isn't found, and just don't setup the plugin in that case. Thanks for your report, closing.
