### ISSUE TITLE
Plug-in to show touch positions

### ISSUE THREAD

**Issue by zougloub** [WayfireWM/wayfire-plugins-extra#261]
It would be nice to have a plugin that can show touch positions on screen, to help with accessibility, or debug touchscreens.

It seems there's a crosshair plug-in in wayfire-plugins-extra that can show mouse pointer position, the idea would be to have something analogue for touchscreen devices.

**Comment by soreau** [comment]
I tested this with stipc using a virtual touch device and the only way I can reproduce this is if the outputs are actually swapped and *not* swapped in config. So maybe you're testing with a minimal config and do not have the output position layout configured?

**Comment by soreau** [comment]
To be clear, the showtouch plugin is in the [showtouch branch](https://github.com/soreau/wayfire-plugins-extra/tree/showtouch) of wayfire-plugins-extra.

**Comment by zougloub** [comment]
> I tested this with stipc using a virtual touch device and the only way I can reproduce this is if the outputs are actually swapped and _not_ swapped in config (or vice versa, the outputs are swapped in config but not physically). So maybe you're testing with a minimal config and do not have the output position layout configured or have inadvertently physically swapped the outputs?

:man_facepalming:  I had swapped the monitors by mistake during transportation. Everything is OK.
