### ISSUE TITLE
Auto Rotate doesnt work on Linx 10

### ISSUE THREAD

**Issue by spikerguy** [WayfireWM/wayfire-plugins-extra#3]
I have been testing Wayfire on my Tablet PC. 
Rotate using the Key press works but not using the sensors.

**Comment by ammen99** [comment]
Do you have iio-sensor-proxy running?

**Comment by spikerguy** [comment]
Yes it worked after installing this, But it works in opposite direction.

**Comment by ammen99** [comment]
Can you launch `monitor-sensor` and see if it outputs the correct orientation?

**Comment by spikerguy** [comment]
It is changing but in opposite direction. So when I rotate right it shows changes to right up I think it should be left up when turned right. Shouldnt it ?

**Comment by ammen99** [comment]
@spikerguy On my system (and I think this is the "expected"):

I turn my laptop counter-clockwise, and I get right-up (right side of laptop is now up)

Is this what you get?

**Comment by spikerguy** [comment]
I turned my tablet clockwise and I get right-up. 
I turned my tablet counter-clockwise and I get left up

**Comment by ammen99** [comment]
Then this is a problem with either your driver or iio-sensor proxy. I recall having similar problems with my old laptop, I ended up patching iio-sensor-proxy itself. But there should be a way to fix this without resorting to patches: https://github.com/hadess/iio-sensor-proxy#accelerometer-orientation

Or maybe look at the issues, I'm pretty sure I have seen this exact issue described somewhere.
