### ISSUE TITLE
join-views not working

### ISSUE THREAD

**Issue by damianatorrpm** [WayfireWM/wayfire-plugins-extra#36]
https://drive.google.com/file/d/1HQeohsmBeZYmhlsWbzssiNA8PntdSvis/view?usp=sharing

**Comment by ammen99** [comment]
The option of move is a private option, not meant to be enabled without join-views. And this bug seems to be in join-views, it is responsible for keeping the dialogue centered.

**Comment by soreau** [comment]
Closing for now, reopen if this is still an issue.
