### ISSUE TITLE
[follow-focus] Focus does not follow the pointer between workspaces on different displays

### ISSUE THREAD

**Issue by nwg-piotr** [WayfireWM/wayfire-plugins-extra#46]
If I move the pointer from one display to another, where the current workspace contains no window, the focus stays at the previous workspace / display. 

Example: 

1. I'm writing this message in workspace 1 on DP-1
2. I'm moving the pointer to WS 1 on eDP-1
3. I'm pressing `<super> KEY_T`

Alacritty opens over the browser window on DP-1.

It seems that pointing a workspace is not enough. A window must be pointed for focus to change - or the workspace needs to be clicked. Could it be improved?

**Comment by soreau** [comment]
Can you see if things work better on the follow-focus branch?

**Comment by nwg-piotr** [comment]
Is there any simple way to do it with the install script?

**Comment by soreau** [comment]
You should be able to run the following from wf-install/wayfire-plugins-extra/ directory:
```
git checkout origin/follow-focus
ninja -C build
ninja -C build install
```

**Comment by nwg-piotr** [comment]
> $ checkout origin/follow-focus
fatal: Unable to create '/home/piotr/Clones/wf-install/wayfire-plugins-extra/.git/index.lock': Permission denied

Do I need sudo?

**Comment by nwg-piotr** [comment]
It looks no better. Previously focusing a window on a new workspace was enough. Now it doesn't work.

**Comment by soreau** [comment]
Ok, thanks for testing. I guess I'll have to plug in another output device.

**Comment by nwg-piotr** [comment]
Any time. This plugin is the last thing needed to make me 100% happy with wayfire.

**Comment by soreau** [comment]
@nwg-piotr Can you try the latest follow-focus branch?

**Comment by nwg-piotr** [comment]
It seems to werk as it should!

**Comment by soreau** [comment]
Great, thanks!

**Comment by nwg-piotr** [comment]
#47 closes the issue.
