### ISSUE TITLE
mag is broken on HiDPI

### ISSUE THREAD

**Issue by myfreeweb** [WayfireWM/wayfire-plugins-extra#57]
mag produces an upside-down image with bizzare mutliple copies effect due to scale=2, see video: https://dl.unrelenting.technology/wf-mag.mp4 (not sure if upside down is due to scale, but the weirdness with copies sure looks like it)

**Comment by soreau** [comment]
This is due to wlroots changes. #58 should fix it.

**Comment by myfreeweb** [comment]
Well, it did fix the inversion, but not HiDPI support

**Comment by soreau** [comment]
> Well, it did fix the inversion, but not HiDPI support

This is how it's always been. I do not have any HiDPI equipment so I don't have much incentive to fix anything related to HiDPI. Patches are welcome, though.

**Comment by soreau** [comment]
(for reference, it was discovered on IRC that HiDPI and it only was seemingly not working due to the cursor being over the mag view, which can make it appear to be broken)

**Comment by ammen99** [comment]
> This is how it's always been. I do not have any HiDPI equipment so I don't have much incentive to fix anything related to HiDPI. Patches are welcome, though.

You don't need any special hardware, just set scale=2 for any monitor (that's what I do for testing) :)

**Comment by soreau** [comment]
> > This is how it's always been. I do not have any HiDPI equipment so I don't have much incentive to fix anything related to HiDPI. Patches are welcome, though.
> 
> You don't need any special hardware, just set scale=2 for any monitor (that's what I do for testing) :)

Ah, thanks.
