### ISSUE TITLE
Integer scaling

### ISSUE THREAD

**Issue by chaoskagami** [WayfireWM/wayfire-plugins-extra#67]
I play a lot of old games. The windows of these old games are beyond tiny on any sufficiently modern display. Some allow changing the window size, but doing so while keeping the aspect ratio is hard (I used xdotool previously for this), and often they end up with filtering (blur) when ideally there would be none (if it's a pixellated game.)

Since wayland doesn't have a lot of the limitations of X11 with how windows are handled (it's all just composited layers), integer scaling via a transform should be possible.

To be clear, I'm not talking about resizing the window. I'm talking about applying a transformation to render the window larger, preferably with configurable filtering.

(I tried to implement a plugin myself by adding a transformer, but it's crashy and I have no idea how to properly handle damage with this, so I'm opening an issue instead. Also, despite the title, this has nothing to do with the scale plugin.)

**Comment by soreau** [comment]
> In any case, thank you very much for the quick work. This is very useful and is (yet another) reason to ditch X11 permanently for me.

No problem.

> I suppose whenever it gets added to wayfire-plugins-extra this issue can be closed?

Yes.

**Comment by soreau** [comment]
>     * Setting the `inc_x_binding`/`inc_y_binding` to the same bind (as well as the same for `dec`) increases the window scale twice via the keyboard combo (so, to 3x size) with `preserve_aspect` enabled. Setting `zoom_step` to 0.5 works around this as does removing one of the binds. The ultimate cause is `delta.x = delta.y = std::max(delta.x, delta.y);` as far as I can tell, it will cause the X transform to apply to both dimensions and then the Y transform as well with `preserve_aspect` since it gets called twice. Might be worth checking if `preserve_aspect` is enabled and immediately returning if processing `y`.
>

This could also be considered a core bug I suppose, [this wayfire patch](http://ix.io/2GLX) fixes the multiple binding issue but I'm not sure if the current behavior is intentional or not.

**Comment by chaoskagami** [comment]
I feel like it's probably intentional, or at very least I don't feel like that patch is desirable. The `command` module's design especially makes me think this; I can think of situations where you might want to call multiple commands on a single keypress and not have to put things in a shell script to do so.

**Comment by ammen99** [comment]
> This could also be considered a core bug I suppose, [this wayfire patch](http://ix.io/2GLX) fixes the multiple binding issue but I'm not sure if the current behavior is intentional or not.

Yes, the current behavior is intentional - you could for ex. use the same binding to make a view sticky and always on top.
