### ISSUE TITLE
crashes when closing app while using force-fullscreen on it

### ISSUE THREAD

**Issue by MrSwedish** [WayfireWM/wayfire-plugins-extra#88]
does it on every app i tried

**Comment by soreau** [comment]
How are you closing the application? Here when I use Alt+F4 or the menu on xfce4-terminal, it doesn't crash wayfire.

**Comment by MrSwedish** [comment]
yeah, i'm alt+f4'ing or clsing via the apps way

**Comment by MrSwedish** [comment]
wait, let me try sometihginh

**Comment by MrSwedish** [comment]
nothing worked

**Comment by soreau** [comment]
What version of wayfire are you using?

**Comment by MrSwedish** [comment]
aur/wayfire 0.7.1-3 (+16 1.02) (Installed)
    3D wayland compositor

**Comment by soreau** [comment]
I'm using latest git but I can't think of anything that has changed that would fix this.. I have tried with native wayland surfaces as well as with xwayland. Does it happen if you force-fullscreen a terminal and type `exit`?

**Comment by soreau** [comment]
It also could be your configuration but the log would be most useful as it should contain a backtrace. Just start wayfire with `wayfire &> /tmp/wayfire.log` then cause the crash and post the log file.

**Comment by MrSwedish** [comment]
> I'm using latest git but I can't think of anything that has changed that would fix this.. I have tried with native wayland surfaces as well as with xwayland. Does it happen if you force-fullscreen a terminal and type `exit`?

yes

**Comment by MrSwedish** [comment]
> It also could be your configuration but the log would be most useful as it should contain a backtrace. Just start wayfire with `wayfire &> /tmp/wayfire.log` then cause the crash and post the log file.

[output](https://gist.github.com/MrSwedish/7b1c751949d876b0407e22f3bd75d3bc)
it dies while trying to save itslef

**Comment by soreau** [comment]
> > It also could be your configuration but the log would be most useful as it should contain a backtrace. Just start wayfire with `wayfire &> /tmp/wayfire.log` then cause the crash and post the log file.
> 
> [output](https://gist.github.com/MrSwedish/7b1c751949d876b0407e22f3bd75d3bc)

This does not contain the backtrace at the end. It does not appear that wayfire crashed in this log. Are you causing wayfire to crash before posting the log?

**Comment by MrSwedish** [comment]
oh, so after the crash?

**Comment by soreau** [comment]
yes and if you have to restart wayfire again to post the log, don't use &> /tmp/wayfire.log because that will overwrite the log file

**Comment by MrSwedish** [comment]
[wafires.log](https://github.com/WayfireWM/wayfire-plugins-extra/files/6642566/wafires.log)
this time I started wayfire from the tty
not from the terminal inside wayfire (lol)

**Comment by soreau** [comment]
Hm, I can't really tell what's going wrong there, but maybe @ammen99 has some idea. Since I can't reproduce here with wayfire git, I'd say try upgrading to latest -git packages and see if the problem persists.

**Comment by MrSwedish** [comment]
alright

**Comment by MrSwedish** [comment]
works on git!

**Comment by MrSwedish** [comment]
but now i don't get audio

**Comment by MrSwedish** [comment]
sorry, the audio thing was just me

**Comment by soreau** [comment]
👍
