### ISSUE TITLE
Provide better readme/documentation

### ISSUE THREAD

**Issue by florhizome** [WayfireWM/wayfire-plugins-extra#97]
The project should at least tell:
- which plugins are included, a short(!) description what they offer and the original repos + author's so that one can contact them directly.
- which plugins are submodules and how to install them
- special dependencies, if needed

optional: where to get if not directly

Contributions to  wiki/further doc, descriptions of usecases could be more encouraged, but I would propose it's better to just keep one wiki (that of wayfire itself, to keep stuff together and encourage interaction) and just link to that.

Right now it is kind of a black box, and requires unnecessary digging to use the package to full extent, or even contribute.

**Comment by soreau** [comment]
The wiki is open to edit and PR's are welcome to update the README.
