### ISSUE TITLE
Disabling input depending on hinge angle

### ISSUE THREAD

**Issue by botiapa** [WayfireWM/wayfire-plugins-extra#98]
I wrote a plugin which disables all input sources except touch when the angle of the hinge exceeds a certain value. Is this something you're interested in adding to this repository?

**Comment by soreau** [comment]
Yes, sounds like it could be useful to others as well. Can you submit a pull request?

**Comment by botiapa** [comment]
I will once I clean everything up.

**Comment by soreau** [comment]
Also we were discussing such a plugin on IRC, it seems there might be a better way than holding a grab. You can use matrix, which is bridged with IRC, and people can reply to you while you're away.

**Comment by botiapa** [comment]
A PR has been accepted, thanks. Closing.
